/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by Keycloakify

export type ThemeName = "my-app-1" | "my-app-2";

export const themeNames: ThemeName[] = ["my-app-1", "my-app-2"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

/* prettier-ignore-end */
